In [1]:
import numpy as np
rng = np.random.default_rng()

# task 1 

A = rng.random(100)

print('среднее арифметическое:', '\n', np.average(A), '\n',
      'медиана:', '\n', np.median(A), '\n',
      'стандартное отклонение:', '\n', np.std(A))

# task 2

X = rng.random((3,3), float)
Y = rng.random((3,3), float)

Res = np.dot(X, Y)

x = np.reshape(X, -1)
y = np.reshape(Y, -1)

result = []

for i in range(9):
    result.append(x[i]*y[i])

print('матричное умножение:', '\n', Res, '\n',
      'поэлементное:', '\n', result, '\n',
      "сумма поэлементного умножения:", '\n', sum(result), '\n', sum(Res))

среднее арифметическое: 
 0.4717884409436627 
 медиана: 
 0.46148819499153304 
 стандартное отклонение: 
 0.2910762896598896
матричное умножение: 
 [[1.07053444 0.50409864 1.29888038]
 [1.20537312 0.57640214 1.31290135]
 [0.68576269 0.33950629 0.80193892]] 
 поэлементное: 
 [np.float64(0.6357445430281757), np.float64(0.344410648977802), np.float64(0.1527950666679815), np.float64(0.32508914568100405), np.float64(0.05024799662068878), np.float64(0.11779851765202233), np.float64(0.21743799312422366), np.float64(0.3554806613457466), np.float64(0.07514534903178786)] 
 сумма поэлементного умножения: 
 2.274149922129433 
 [2.96167025 1.42000707 3.41372064]
